services:
  event.admin:
    class: EventBundle\Admin\EventAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Content", label: "Event" }
    arguments:
      - ~
      - EventBundle\Entity\Event
      - ~
    calls:
      - [ setTranslationDomain, [EventBundle]]
    public: true

  user.event.admin:
    class: EventBundle\Admin\UserEventAdmin
    tags:
    - { name: sonata.admin, manager_type: orm, group: "Content", label: "Event_USER", show_in_dashboard: false }
    arguments:
    - ~
    - EventBundle\Entity\UserEvent
    - ~
    calls:
    - [ setTranslationDomain, [EventBundle]]
    public: false

  message.admin:
    class: EventBundle\Admin\EventAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Content" }
    arguments:
      - ~
      - EventBundle\Entity\Event
      - EventBundle\Controller\MessageController