services:
  app.admin.user:
    class: UserBundle\Admin\UserAdmin
    tags:
      - { name: sonata.admin, manager_type: orm, group: "Content", label: "Users" }
    arguments:
      - ~
      - UserBundle\Entity\User
      - ~
    calls:
      - [ setTranslationDomain, [EventBundle]]
    public: true

#      - UserBundle\Entity\User

  app.admin.user.account:
    class: UserBundle\Admin\UserAccountAdmin
    arguments: [~, UserBundle\Entity\UserAccount, ~]
    tags:
      - { name: sonata.admin, manager_type: orm, show_in_dashboard: false }
    calls:
      - [ setTranslationDomain, [admin]]
    public: false