security_login:
  path: /login
  defaults: { _controller: UserBundle:Security:login }

security_logout:
  path: /logout
  defaults: { _controller: UserBundle:Security:logout }

register:
  path: /register
  defaults: { _controller: UserBundle:Security:register }

recover:
  path: /recover/{token}
  defaults: { _controller: UserBundle:Security:recover, token: null }

user:
  path: /user

user_password_recover:
  path: /user/recover-password
  defaults: { _controller: UserBundle:User:recoverPassword }
#
#user_own_edit:
#  path: /user/edit
#
#user_view:
#  path: /user/{is}
#
#user_edit:
#  path: /user/{id}/edit