admin_login:
  path: /admin/login
  defaults: { _controller: UserBundle:Admin:login}

admin_logout:
  path: /admin/logout
  defaults: { _controller: UserBundle:Admin:logout}

admin_check:
  path: /admin/check
  defaults: { _controller: UserBundle:Admin:check}

security_login:
  path: /login
  defaults: { _controller: UserBundle:Security:login }

security_logout:
  path: /logout
  defaults: { _controller: UserBundle:Security:logout }

register:
  path: /register
  defaults: { _controller: UserBundle:Security:register }

recover:
  path: /recover/{token}
  defaults: { _controller: UserBundle:Security:recover, token: null }

user:
  path: /user

user_password_recover:
  path: /user/recover-password
  defaults: { _controller: UserBundle:User:recoverPassword }
#
#user_own_edit:
#  path: /user/edit
#
user_view:
  path: /user/{id}
  defaults: { _controller: UserBundle:User:view }
#
#user_edit:
#  path: /user/{id}/edit