app:
    resource: '@AppBundle/Controller/'
    type: annotation

User:
    resource: '@UserBundle/Resources/config/routing.yml'

event:
    resource: '@EventBundle/Resources/config/routing.yml'

admin_area:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin